formsaurus/manage/urls.py
from django.urls import path
from formsaurus.manage import views as manage
from formsaurus import views

app_name = 'formsaurus_manage'
urlpatterns = [
    path('manage', manage.ManageView.as_view(), name='manage'),
    path('manage/form/add', manage.SurveyAddView.as_view(), name='survey_add'),
    path('manage/form/create/<uuid:survey_id>',
         manage.SurveyWizardView.as_view(), name='survey_wizard'),
    path('manage/form/edit/<uuid:survey_id>',
         manage.SurveyEditView.as_view(), name='survey_edit'),
    path('manage/form/preview/<uuid:survey_id>',
         views.SurveyView.as_view(), name='survey_preview'),
    path('manage/form/publish/<uuid:survey_id>',
         manage.PublishSurveyView.as_view(), name='survey_publish'),
    path('manage/form/create/<uuid:survey_id>/show_branding/toggle',
          manage.ToggleShowBrandingView.as_view(), name='toggle_show_branding'),
    path('manage/form/create/<uuid:survey_id>/add',
         manage.AddQuestionView.as_view(), name='survey_add_question'),
    path('manage/form/create/<uuid:survey_id>/add/<slug:question_type>',
         manage.AddQuestionView.as_view(), name='survey_add_question'),
    path('manage/form/create/<uuid:survey_id>/edit/<uuid:question_id>',
         manage.EditQuestionView.as_view(), name='survey_edit_question'),
    path('manage/form/create/<uuid:survey_id>/delete/<uuid:question_id>',
         manage.DeleteQuestionView.as_view(), name='delete_question'),
    path('manage/form/create/<uuid:survey_id>/up/<uuid:question_id>',
         manage.QuestionUpView.as_view(), name='question_up'),
    path('manage/form/create/<uuid:survey_id>/down/<uuid:question_id>',
         manage.QuestionDownView.as_view(), name='question_down'),
    path('manage/form/create/<uuid:survey_id>/logic/<uuid:question_id>',
         manage.LogicView.as_view(), name='question_logic'),
    path('manage/form/create/<uuid:survey_id>/field',
         manage.HiddenFieldView.as_view(), name='survey_add_hidden_field'),
    path('manage/form/delete/<uuid:survey_id>',
         manage.DeleteSurveyView.as_view(), name='survey_delete'),
    path('manage/form/list', manage.SurveysView.as_view(), name='surveys'),
    path('manage/form/submissions/<uuid:survey_id>',
         manage.SubmissionsView.as_view(), name='submissions'),
    path('manage/form/submissions/<uuid:survey_id>/<uuid:submission_id>',
         manage.SubmissionView.as_view(), name='submission'),

    path('manage/search/unsplash', manage.UnsplashSearchView.as_view(),
         name='unsplash_search'),
    path('manage/search/pexels', manage.PexelsSearchView.as_view(),
         name='pexels_search'),
    path('manage/search/tenor', manage.TenorSearchView.as_view(),
         name='tenor_search'),
]

formsaurus/urls.py
from django.urls import path
from formsaurus import views

app_name = 'formsaurus'
urlpatterns = [
    path('form/<uuid:survey_id>', views.SurveyView.as_view(), name='survey'),
    path('form/<uuid:survey_id>/<uuid:question_id>/<uuid:submission_id>',
         views.QuestionView.as_view(), name='question'),
    path('form/completed/<uuid:survey_id>/<uuid:submission_id>',
         views.CompletedView.as_view(), name='completed'),
    path('form/closed/<uuid:survey_id>',
         views.ClosedView.as_view(), name='closed'),

]

formsaurus/templates/formsaurus/closed.html
{% extends "formsaurus/skeleton.html" %}

{% block content %}
<div class="vertical-center">
    <main class="container">
        <div class="row">
            <div class="col">
                <h1 class="display-3">Survey is Closed</h1>
                <p class="lead">Create your own forms on formsaurus.com.</p>
                <p><a href="{% url 'formsaurus_manage:manage' %}'" class="btn btn-primary btn-lg btn-wide">Get Started</a></p>

                {% if submission.is_preview %}
                    <p class="m-0">
                        <a href="{% url 'formsaurus_manage:survey_wizard' survey.id %}" class="text-muted">&laquo; Back to Edit Survey</a>
                    </p>
                {% endif %}
            </div>
        </div>
    </main>
</div>
{% endblock %}

formsaurus/templates/formsaurus/completed.html
{% extends "formsaurus/skeleton.html" %}

{% block content %}
<div class="vertical-center">
    <main class="container">
        <div class="row">
            <div class="col">     
                <h1 class="display-3">Survey Completed</h1>
                <p class="lead">Create your own forms on formsaurus.com.</p>
                <p><a href="{% url 'formsaurus_manage:manage' %}'" class="btn btn-primary btn-lg btn-wide">Get Started</a></p>
                    
                {% if submission.is_preview %}
                    <p class="m-0">
                        <a href="{% url 'formsaurus_manage:survey_wizard' survey.id %}" class="text-muted">&laquo; Back to Edit Survey</a>
                    </p>
                {% endif %}
            </div>
        </div>
    </main>
</div>
{% endblock %}

formsaurus/templates/formsaurus/skeleton.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block head %}{% endblock %}
    <title>{% block title %}Formsaurus{% endblock %}</title>
    <style>
    .fake-button {
        background: transparent !important;
        border: 0;
        outline: 0;
        box-shadow: none !important;
    }
    .vertical-center {
        min-height: 100%;  /* Fallback for browsers do NOT support vh unit */
        min-height: 100vh; /* These two lines are counted as one :-)       */

        display: flex;
        align-items: center;
    }

    @media (min-width: 768px) {
        .vertical-md-center {
            min-height: 100%;  /* Fallback for browsers do NOT support vh unit */
            min-height: 100vh; /* These two lines are counted as one :-)       */

            display: flex;
            align-items: center;
        }
    }


    input.choice, button.choice {
        min-width: 150px;
        max-width: 100%;
    }
    input.opinion {
        min-width: 40px;
    }
    input.survey-input:focus, input.survey-input  {
        background: transparent !important;
        border: 0;
        outline: 0;
        box-shadow:none !important;
        font-size: 30px;
        width: 100%;
        border-bottom: 1px solid #eeeeee;
    }
    textarea.survey-input:focus,textarea.survey-input {
        background: transparent !important;
        width: 100%;
        resize: none;
        outline: none;
        overflow: hidden;
        border: 0;
        box-shadow: none !important;
        font-size: 30px;
        border-bottom: 1px solid #eeeeee;
    }
    .choice {
        cursor: pointer;
        display: inline-block;
        font-weight: 400;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        border: 1px solid transparent;
        border-radius: .25rem;
        text-transform: none;
        padding: 0.375rem 0.75rem;
        text-decoration: none;
    }

    .choice-selected {
        color: #ffffff;
        background-color: #007bff;
        border-color: #007bff;
    }

    .choice-unselected {
        color: #007bff;
        background-color: transparent;
        background-image: none;
        border-color: #007bff;
    }

    /* MANAGE */
    .btn-wide {
        min-width: 150px;
    }
    input.title:focus, input.title  {
        background: transparent !important;
        border: 0;
        outline: 0;
        box-shadow:none !important;
        font-size: 30px;
        width: 100%;
        border-bottom: 1px solid #cccccc;
    }
    .text-lg {
          font-size: 1.5rem;
      }
      .text-sm {
          font-size: 0.75rem;;
      }
      .text-upper {
          text-transform: uppercase;
      }
      .border-r {
          border-right: 1px solid #d2d6dc;
      }

      .bd-callout {
            padding: 1.25rem;
            margin-top: 1.25rem;
            margin-bottom: 1.25rem;
            border: 1px solid #eee;
            border-left-width: .25rem;
            border-radius: .25rem;
        }

        .bd-callout-warning {
            border-left-color: #f0ad4e;
        }

        .bd-callout-info {
            border-left-color: #5bc0de;
        }
    </style>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/3734b7d9ee.js" crossorigin="anonymous"></script>
    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <!-- Pickaday -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css">
    <!-- IntTelInput -->
    <link rel="stylesheet" type="text/css" href="{% static 'intl-tel-input/css/intlTelInput.min.css' %}"/>
    <!-- Stripe -->
    <script src="https://js.stripe.com/v3/"></script>
</head>

<body style="position: relative;">
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <!-- Select2 -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <!-- Moment -->
    <script src="{% static 'moment-with-locales.js' %}"></script>
    <!-- Pickaday -->
    <script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
</body>
</html>

formsaurus/templates/formsaurus/survey_add_hidden_field.html
{% extends 'formsaurus/skeleton.html' %}


{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h4><a href="{% url 'formsaurus:survey_wizard' survey.id %}">{{ survey.name }}</a></h4>
            <h1>Add Field</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="name" class="w-100 mb-2 title" placeholder="email" autofocus required/>
                    <label for="button_label"><small class="text-muted">Name</small></label>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Add">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

formsaurus/templates/formsaurus/survey_wizard.html
{% extends 'formsaurus/skeleton.html' %}
{% load formsaurus %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h1>{{ survey.name }}</h1>
        </div>
        <div class="col-1 pt-4">
            <div class="custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" id="show_image_switch" {% if question.published %}checked{% endif %}>
                <label class="custom-control-label" for="show_image_switch">Published</label>
            </div>                

        </div>
    </div>
    <div class="row mt-5">
        <div class="col-2">
            {% if not question.published %}
                <p><a href="{% url 'formsaurus:survey_add_hidden_field' survey.id %}" class="btn btn-primary">Add Hidden Field</a></p>
                <p><a href="{% url 'formsaurus:survey_add_question' survey.id %}" class="btn btn-primary">Add Question</a></p>
                <p><a href="{% url 'formsaurus:survey_delete' survey.id %} " class="btn btn-danger {% if survey.published %}disabled{% endif %}">Delete</a></p>
            {% endif %}
        </div>
        <div class="col">
            {% if survey.hiddenfield_set.all %}
            <h2>Fields</h2>
            <table class="table">
                <tbody>
                    {% for field in survey.hiddenfield_set.all %}
                    <tr><td>{{ field.name }}</td></tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
                <p class="text-muted">No hidden fields in this form.</p>
            {% endif %}

            {% if survey.question_set.all %}
            <h2>Questions</h2>
            <table class="table">
                <tbody>
                    {% for question in survey.question_set.all %}
                        <tr>
                            <td class="text-muted">{{ forloop.counter }}</td>
                            <td class="text-muted">{{ question.question_type|question_type_name }}</td>
                            <td>{{ question.question }}</td>
                            <td>
                                <div class="custom-control custom-switch">
                                    <input type="checkbox" class="custom-control-input" disabled id="show_image_switch" {% if question.required %}checked{% endif %}>
                                    <label class="custom-control-label" for="show_image_switch"></label>
                                </div>                
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
                <p class="text-muted">No questions in this form.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

formsaurus/templates/formsaurus/video.html
<!-- VIDEO -->
{% if question.parameters.video.source == 'youtube' %}
    <div id="player"></div>
    <script>
        var tag = document.createElement('script')
        tag.src = 'https://www.youtube.com/iframe_api'
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        var player;
        function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
            width: '1280',
            height: '720',
            videoId: '{{ question.parameters.video.video_id }}',
            playerVars: {
                'autoplay': 1,
                'controls': 0,
                'disablekb': 1,
                'fs': 0,
                'loop': 1,
                'modestbranding': 1,
                'playlist': '{{ question.parameters.video.video_id }}',

            },
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
            });
        }
        function onPlayerReady(event) {
            event.target.f.style = "{{ style }}; object-fit: cover; object-position: {{ question.parameters.position_x}}% {{ question.parameters.position_y }}%; opacity: {{ question.parameters.opacity }}%;"
            event.target.f.allowfullscreen="0"
            event.target.mute()
        }
        function onPlayerStateChange(event) {
        }
    </script>
{% else %}
    <video autoplay="autoplay" loop="true" muted style="{{ style }}; object-fit: cover; object-position: {{ question.parameters.position_x}}% {{ question.parameters.position_y }}%; opacity: {{ question.parameters.opacity }}%;">
        <source src="{{ question.parameters.video.url }}" type="video/mp4">
    </video>
{% endif %}